config/routes.rb
Rails.application.routes.draw do

  resources :conversations do
    member do
      post 'read'
    end
  end
  resources :messages, only: [:create, :new, :destroy] do
    member do
      get 'reply'
    end
  end
  resources :blockings, only: [:create, :index, :destroy]
  resources :homes, only: [:index]
  devise_for :users
  resources :users do
    member do
      post 'block'
      post 'unblock'
    end
  end
  root to: 'homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blocking.rb
class Blocking < ActiveRecord::Base
  belongs_to :user
  belongs_to :blocked_user, class_name: 'User'

  validates :user_id, uniqueness: {
    scope: [:blocked_user_id],
    message: 'User already blocked.'
  }

  validate :only_different_user_and_blocked_user

  def only_different_user_and_blocked_user
    errors.add(:user,'is the same as Blocked user.') if user_id == blocked_user_id
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :receiver, foreign_key: 'receiver_id', class_name: 'User'
  belongs_to :sender, foreign_key: 'sender_id', class_name: 'User'

  def other_member(current_user)
    if current_user == sender
      user = receiver
    else
      user = sender
    end
    user
  end

  def unread_message(current_user)
    ShowUnreadMessagesInConversation.new(current_user, self).call
  end

  def update_messages
    messages.each do |message|
      message.update_attribute(:read, true) if current_user == message.receiver
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :receiver, foreign_key: 'receiver_id', class_name: 'User'
  belongs_to :sender, foreign_key: 'sender_id', class_name: 'User'

  validates_presence_of :body, :description, :receiver_id
  validate :only_different_sender_and_receiver

  after_create :create_or_update_conversation
  
  def only_different_sender_and_receiver
    errors.add(:receiver,'is the same as Sender.') if sender_id == receiver_id
  end 

  def create_or_update_conversation
    conversation = Conversation.find_by(receiver: receiver, sender: sender) || Conversation.find_by(receiver: sender, sender: receiver)
    conversation = Conversation.create(receiver: receiver, sender: sender) if conversation.nil?
    conversation.messages << self if conversation
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :blocked_users, foreign_key: 'user_id', class_name: 'Blocking'
  has_many :as_blocked_users, foreign_key: 'blocked_user_id', class_name: 'Blocking'
  has_many :created_conversations, foreign_key: 'sender_id', class_name: 'Conversation'
  has_many :member_conversations, foreign_key: 'receiver_id', class_name: 'Conversation'
  has_many :received_conversations, foreign_key: 'recipient_id'
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'Message'
  has_many :received_messages, foreign_key: 'receiver_id', class_name: 'Message'
  
  before_validation :set_default_role 

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    role == 'admin'
  end

  private
  
  def set_default_role
  	self.role ||= 'user'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :first_name, :last_name, :city)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name, :city)
    end
  end
end

app/controllers/blockings_controller.rb
class BlockingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blocking, only: [:destroy]

  def index
    @blockings = BlockingUser.new(current_user: current_user).blocked_users
  end

  def create
    begin
      CreateBlocking.new(blocking_params).call
      flash[:notice] = 'User was blocked.'
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to root_path
  end

  def destroy
    begin
      DestroyBlocking.new(@blocking).call
      flash[:notice] = 'User was unblocked.'
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to root_path
  end

  private
    
  def set_blocking
    @blocking = Blocking.find(params[:id])
  end

  def blocking_params
    params.require(:blocking).permit(:user_id,:blocked_user_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def read
    @conversation = Conversation.find(params[:id])
    update_messages

    flash[:notice] = 'You have read messages.'
    redirect_to root_path
  end

  private

  def update_messages
    @conversation.messages.each do |message|
      message.update_attribute(:read, true) if current_user == message.receiver
    end
  end 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = ShowConversation.new(current_user).call
    @message = Message.new
    @blocking = Blocking.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:destroy ,:reply]

  def new
    @message = Message.new
    @blocking = BlockingUser.new(current_user: current_user).blocking
  end

  def create
    begin
      CreateMessage.new(current_user, message_params).call
      flash[:notice] = 'Message was successfully created.'
      redirect_to root_path
    rescue Exception => e
      flash[:notice] = e.message
      redirect_to new_message_path
    end
  end

  def destroy
    begin
      DestroyMessage.new(@message).call
      flash[:notice] = 'Message was successfully destroyed.'
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to root_path
  end

  def reply
    begin
      ReplyMessage.new(@message).call
      flash[:notice] = 'Message was successfully replied.'
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to root_path
  end

  private

    def set_message
      @message = Message.find_by(id: params[:id])
    end

    def message_params
      params.require(:message).permit(:body, :description, :receiver_id, :sender_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order(:first_name)
  end

  def show
  end
  
  def edit
  end

  def new
    @user = User.new
  end

  def create
    begin
      factory = CreateUser.new(user_params)
      factory.call
      flash[:notice] = "User was successfully created."
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to users_path
  end

  def update
    begin
      factory = UpdateUser.new(@user, user_params)
      factory.call
      flash[:notice] = "User was successfully updated."
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to user_path(@user)
  end

  def destroy
    begin
      factory = DestroyUser.new(@user)
      factory.call
      flash[:notice] = "User was successfully destroyed."
    rescue Exception => e
      flash[:notice] = e.message
    end

    redirect_to users_path
  end

  private
    
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :city, :email, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin_user!
    unless current_user.admin?
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'You are not admin ' }
      end
    end
  end

  def unread_messages
    ShowUnreadMessages.new(current_user).call
  end

  def show_active(i)
    'in active' if i == 0
  end

  def find_blocking(current_user, blocked_user)
    Blocking.find_by(user_id: current_user.id, blocked_user_id: blocked_user.id)
  end
end

app/views/blockings/index.html.haml
%h1 Blocked Users
- if @blockings.present?
  %table.table.table-bordered
    %thead
      %tr.info
        %th #
        %th Full name
        %th Email
        %th City
        %th 
    %tbody
      - @blockings.each do |blocking|
        %tr
          %td= blocking.blocked_user.id
          %td= blocking.blocked_user.full_name
          %td= blocking.blocked_user.email
          %td= blocking.blocked_user.city
          %td= link_to "Unblock user", blocking, method: :delete, class: 'btn btn-danger'
- else
  .alert.alert-danger You haven't blocked users

app/views/homes/_conversation.html.haml
.col-lg-9
  .tab-content
    - @conversations.each_with_index do |conversation, i|
      %div{id: "conversation_#{conversation.id}", class: "tab-pane face #{show_active(i)}"}
        Conversation with
        %b
          = conversation.other_member(current_user).full_name
        %hr
        #message-scroll
          - conversation.messages.each do |message|
            - if current_user == message.sender
              .media.msg
                %a.pull-right
                  = image_tag('1.png', style: "width: 40px; height: 40px;")
                .media-body.alert.alert-success
                  %small.pull-right.time
                    %i.fa.fa-clock-o
                      = message.created_at
                  %h5.media-heading
                    = message.sender.full_name
                    - if find_blocking(conversation.other_member(current_user), current_user).nil?
                      %small
                        = link_to 'Reply', reply_message_path(message)
                        = link_to 'Destroy', message_path(message), method: :delete
                  %small.col-lg-10= message.description
            - else
              .media.msg
                %a.pull-left
                  = image_tag('1.png', style: "width: 40px; height: 40px;")
                .media-body.alert.alert-info
                  %small.pull-right.time
                    %i.fa.fa-clock-o
                      = message.created_at
                  %h5.media-heading= message.sender.full_name
                  %small.col-lg-10= message.description
        %hr
          .send-wrap
            - if find_blocking(conversation.other_member(current_user), current_user).nil?
              = form_for @message do |f|
                = f.hidden_field :sender_id, value: current_user.id
                = f.hidden_field :receiver_id, value: conversation.other_member(current_user).id, id: 'message'
                = f.hidden_field :body, value: 'Body'
                = f.text_area :description, class: 'form-control', rows: '3'
                .btn-panel
                  = f.submit 'Send Message', class: 'btn btn-primary pull-right'
            .btn-panel
              = link_to 'I have read all!!!', read_conversation_path(conversation), method: :post,class: 'btn btn-success'
              - if find_blocking(current_user, conversation.other_member(current_user))
                = link_to "Unblock user", find_blocking(current_user, conversation.other_member(current_user)), method: :delete, class: 'btn btn-danger' 
              - else
                = form_for(@blocking, html:{ class: "inline-form"}) do |f|
                  = f.hidden_field :user_id, value: current_user.id
                  = f.hidden_field :blocked_user_id, value: conversation.other_member(current_user).id
                  = f.submit 'Block user', class: 'btn btn-warning'

app/views/homes/index.html.haml
- if unread_messages > 0
  .alert.alert-danger
    %p#notice You have #{unread_messages} unread messages

.container
  .row
    .col-lg-3
      .btn-panel.btn-panel-conversation
        = link_to 'New message', new_message_path, class: 'btn btn-primary col-lg-6 send-message-btn'
  %hr
.row
  .col-lg-3
    #conversation-scroll
      - if @conversations.present?
        %ul.nav.nav-pills.nav-stacked
          - @conversations.each do |conversation|
            %li.active
              .media.conversation
                %a.pull-left{ :href => "#"}
                  = image_tag('1.png', style: "width: 50px; height: 50px;")
                - if conversation.unread_message(current_user) > 0
                  %h4.unread-messages.pull-right= conversation.unread_message(current_user)
                .media-body
                  %h4.media-heading
                  %a.pull-left{"data-toggle" => "tab", :href => "#conversation_#{conversation.id}"}
                    = conversation.sender.full_name
                  %br
                  %small= conversation.messages.last.description
            %hr
  = render partial: 'homes/conversation'

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to 'Tickets', root_path, class: 'navbar-brand'%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <%= render partial: 'layouts/list_menu' %>
        <li><%= link_to 'Exit', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_list_menu.html.erb
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <%= current_user.full_name %>
        <span class="caret"></span>
    </a>

    <ul class="dropdown-menu" role="menu">
      <li><%= link_to'Edit profile', edit_user_registration_path(current_user) %></li>
      <li class="divider"></li>
      <li><%= link_to  'Blocked users', blockings_path %></li>
      <% if current_user.admin? %>
        <li><%= link_to  'Users', users_path %></li>
      <% end %>
    </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header'%>
    <div class="container">
      <%if notice %>
        <div class="alert alert-success">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <p id="notice"><%= notice %></p>
        </div>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for message do |f|
      - if message.errors.any?
        .alert.alert-danger
          %ul
            - message.errors.full_messages.each do |msg|
              %li= msg
      .panel.panel-primary
        .panel-heading Fill fields
        .panel-body
          .control-group
            = f.hidden_field :sender_id, value: current_user.id
            = f.label :body
            .controls
              = f.text_field :body, value: 'Body', class: 'form-control'
          .control-group
            = f.label :description
            .controls
              = f.text_area :description, class: 'form-control'
          .control-group
            = f.label :receiver
            .controls
              = f.select :receiver_id, User.where.not(id: [@blocking, current_user.id].flatten).collect{ |p| [p.full_name, p.id] }, { include_blank: true, class: 'form-control'}
      .panel.panel-primary
        .panel-body
          = f.submit 'Send', class: "btn btn-block btn-primary"

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>
<%= render 'form', message: @message %>
<%= link_to 'Back', root_path %>

app/views/users/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = form_for user do |f|
      - if user.errors.any?
        .alert.alert-danger
          %ul
            - user.errors.full_messages.each do |msg|
              %li= msg
      .panel.panel-primary
        .panel-heading Fill all fields
        .panel-body
          .control-group
            = f.label :email
            .controls
              = f.email_field :email, autofocus: true, class: 'form-control'
          .control-group
            = f.label :first_name
            .controls
              = f.text_field :first_name, class: 'form-control'
          .control-group
            = f.label :last_name
            .controls
              = f.text_field :last_name, class: 'form-control'
          .control-group
            = f.label :city
            .controls
              = f.text_field :city, class: 'form-control'
          .control-group
            = f.label :role
            .controls
              = f.select :role, [['User', :user],['Admin', :admin]]
          .control-group
            = f.label :password
            .controls
              = f.password_field :password, autocomplete: "off", class: 'form-control'
            .control-group
            = f.label :password_confirmation
            .controls
              = f.password_field :password_confirmation, autocomplete: "off", class: 'form-control'
      .panel.panel-primary
        .panel-body
          = f.submit 'Save', class: "btn btn-block btn-primary"

app/views/users/edit.html.erb
<h1>Редагування профілю</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<%= link_to 'Create', new_user_path, class: 'btn btn-success' %>

<h1>Users</h1>
<table class="table table-bordered">
  <thead>
  <tr class="info">
    <th>#</th>
    <th>Full name</th>
    <th>Email</th>
    <th>City</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><%= user.city %></td>
      <td>
        <%= link_to 'Show', user, class: 'btn btn-success' %>
        <% if current_user != user %>
          <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary' %>
          <%= link_to 'Remove', user, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
        <%end%>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p><b>First name:</b> <%= @user.first_name%></p>
<p><b>Last name:</b> <%= @user.last_name%></p>
<p><b>City:</b> <%= @user.city%></p>
<% if current_user && current_user.admin? %>
  <p><b>Роль:</b> <%= @user.role.capitalize %></p>
<%end%>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>